package com.mycompany.mvc;

import java.awt.GraphicsDevice;
import static java.awt.GraphicsDevice.WindowTranslucency.PERPIXEL_TRANSLUCENT;
import static java.awt.GraphicsDevice.WindowTranslucency.PERPIXEL_TRANSPARENT;
import static java.awt.GraphicsDevice.WindowTranslucency.TRANSLUCENT;
import java.awt.GraphicsEnvironment;



/**
 *
 * @author fabri
 */
public class ViewCalculator extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewCalculator.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public ViewCalculator() {
        super("Calculator 360");
        initComponents();
        //tryCircle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new PanelCircular();
        btnFive = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnOne = new javax.swing.JButton();
        btnData = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnAvg = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        btnProduct = new javax.swing.JButton();
        txtContent = new java.awt.TextField();
        btnClear = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnBinary = new javax.swing.JButton();
        btnPrime = new javax.swing.JButton();
        btnStore = new javax.swing.JButton();
        btnDecimal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setShape(getShape());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBackground.setBackground(new java.awt.Color(204, 255, 51));
        pnlBackground.setForeground(new java.awt.Color(255, 153, 153));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFive.setText("5");
        pnlBackground.add(btnFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 51, 51));

        btnZero.setText("0");
        pnlBackground.add(btnZero, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 51, 51));

        btnThree.setText("3");
        pnlBackground.add(btnThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 51, 51));

        btnEight.setText("8");
        pnlBackground.add(btnEight, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, 51, 51));

        btnFour.setText("4");
        pnlBackground.add(btnFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 51, 51));

        btnOne.setText("1");
        pnlBackground.add(btnOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 51, 51));

        btnData.setText("data");
        pnlBackground.add(btnData, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 130, 50));

        btnTwo.setText("2");
        pnlBackground.add(btnTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 51, 51));

        btnSeven.setText("7");
        pnlBackground.add(btnSeven, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 51, 51));

        btnSix.setText("6");
        pnlBackground.add(btnSix, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 51, 51));

        btnNine.setText("9");
        pnlBackground.add(btnNine, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 51, 51));

        btnDivision.setText("/");
        pnlBackground.add(btnDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 51, 51));

        btnAvg.setText("avg");
        pnlBackground.add(btnAvg, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 90, 50));

        btnAdd.setText("+");
        pnlBackground.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 51, 51));

        btnSub.setText("-");
        pnlBackground.add(btnSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 51, 51));

        btnProduct.setText("*");
        pnlBackground.add(btnProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 51, 51));
        pnlBackground.add(txtContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 430, 60));

        btnClear.setText("C");
        pnlBackground.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 51, 51));

        btnEqual.setText("=");
        pnlBackground.add(btnEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 51, 60));

        btnBinary.setText("binario");
        pnlBackground.add(btnBinary, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 161, 130, 50));

        btnPrime.setText("primo");
        pnlBackground.add(btnPrime, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 130, 50));

        btnStore.setText("m+");
        pnlBackground.add(btnStore, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 90, 50));

        btnDecimal.setText(".");
        pnlBackground.add(btnDecimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 51, 51));

        getContentPane().add(pnlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdd;
    public javax.swing.JButton btnAvg;
    public javax.swing.JButton btnBinary;
    public javax.swing.JButton btnClear;
    public javax.swing.JButton btnData;
    public javax.swing.JButton btnDecimal;
    public javax.swing.JButton btnDivision;
    public javax.swing.JButton btnEight;
    public javax.swing.JButton btnEqual;
    public javax.swing.JButton btnFive;
    public javax.swing.JButton btnFour;
    public javax.swing.JButton btnNine;
    public javax.swing.JButton btnOne;
    public javax.swing.JButton btnPrime;
    public javax.swing.JButton btnProduct;
    public javax.swing.JButton btnSeven;
    public javax.swing.JButton btnSix;
    public javax.swing.JButton btnStore;
    public javax.swing.JButton btnSub;
    public javax.swing.JButton btnThree;
    public javax.swing.JButton btnTwo;
    public javax.swing.JButton btnZero;
    private javax.swing.JPanel pnlBackground;
    public java.awt.TextField txtContent;
    // End of variables declaration//GEN-END:variables

    private void tryCircle() {
        // Determine what the default GraphicsDevice can support.
        GraphicsEnvironment ge =
            GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gd = ge.getDefaultScreenDevice();

        boolean isUniformTranslucencySupported =
            gd.isWindowTranslucencySupported(TRANSLUCENT);
        boolean isPerPixelTranslucencySupported =
            gd.isWindowTranslucencySupported(PERPIXEL_TRANSLUCENT);
        boolean isShapedWindowSupported =
            gd.isWindowTranslucencySupported(PERPIXEL_TRANSPARENT);
        
        
    }
}
